name: Publish API documentation (snapshot)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-doc-snapshot:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and prepare documentation
        uses: eclipse-keypop/keypop-actions/doxygen@v2
        with:
          repo-name: ${{ github.event.repository.name }}

      - name: Deploy to doc branch
        run: |
          git config --global user.name "Eclipse Keypop Bot"
          git config --global user.email "${{ github.repository }}-bot@eclipse.org"
          cd ${{ github.event.repository.name }}
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update snapshot documentation"
          git push origin doc --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
