name: Publish API documentation (snapshot)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-doc-snapshot:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and prepare documentation
        uses: eclipse-keypop/keypop-actions/doxygen@v1
        with:
          repo-name: ${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
          user_name: "Eclipse Keypop Bot"
          user_email: "${{ github.repository }}-bot@eclipse.org"
          commit_message: 'docs: update snapshot documentation'