name: Publish API documentation (release)
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (ex: 1.0.0)'
        required: true

jobs:
  publish-doc-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and prepare documentation
        uses: eclipse-keypop/keypop-actions/doxygen@v2
        with:
          working-directory: .github/doxygen/
          doxyfile-path: ./Doxyfile
      - name: Prepare Doxygen doc page locally
        working-directory: .
        run: ./.github/scripts/prepare_doxygen.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Deploy Doxygen documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
