name: Publish API documentation (snapshot)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-doc-snapshot:
    uses: eclipse-keypop/keypop-actions/.github/workflows/reusable-publish-doxygen.yml@main
    secrets: inherit